# 描述 Compose 文件的版本信息
version: "3.8"

# 定义服务，可以多个
services:
  redis-6371: # 服务名称
    image: redis # 创建容器时所需的镜像
    container_name: redis-6371 # 容器名称
    restart: always # 容器总是重新启动
    network_mode: "host" # host 网络模式
    volumes: # 数据卷，目录挂载
      - ./conf/redis_6371.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis_6371:/data
    command: redis-server /usr/local/etc/redis/redis.conf # 覆盖容器启动后默认执行的命令

  redis-6372:
    image: redis
    container_name: redis-6372
    network_mode: "host"
    volumes:
      - ./conf/redis_6372.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis_6372:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6373:
    image: redis
    container_name: redis-6373
    network_mode: "host"
    volumes:
      - ./conf/redis_6373.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis_6373:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6374:
    image: redis
    container_name: redis-6374
    network_mode: "host"
    volumes:
      - ./conf/redis_6374.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis_6374:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6375:
    image: redis
    container_name: redis-6375
    network_mode: "host"
    volumes:
      - ./conf/redis_6375.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis_6375:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6376:
    image: redis
    container_name: redis-6376
    network_mode: "host"
    volumes:
      - ./conf/redis_6376.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis_6376:/data
    command: redis-server /usr/local/etc/redis/redis.conf
