// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: chi_pai_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 吃牌推送
type C2SChiPaiPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SChiPaiPush) Reset() {
	*x = C2SChiPaiPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chi_pai_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChiPaiPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChiPaiPush) ProtoMessage() {}

func (x *C2SChiPaiPush) ProtoReflect() protoreflect.Message {
	mi := &file_chi_pai_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChiPaiPush.ProtoReflect.Descriptor instead.
func (*C2SChiPaiPush) Descriptor() ([]byte, []int) {
	return file_chi_pai_push_proto_rawDescGZIP(), []int{0}
}

// S -> C 吃牌推送
type S2CChiPaiPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatSeq   int32 `protobuf:"varint,1,opt,name=SeatSeq,proto3" json:"SeatSeq,omitempty"`     // 碰牌的玩家座位方位
	Card1     int32 `protobuf:"varint,2,opt,name=Card1,proto3" json:"Card1,omitempty"`         // 吃牌形成顺子中的第一张牌
	Card2     int32 `protobuf:"varint,3,opt,name=Card2,proto3" json:"Card2,omitempty"`         // 吃牌形成顺子中的第二张牌
	BeEatCard int32 `protobuf:"varint,4,opt,name=BeEatCard,proto3" json:"BeEatCard,omitempty"` // 被吃的牌
	BeSeatSeq int32 `protobuf:"varint,5,opt,name=BeSeatSeq,proto3" json:"BeSeatSeq,omitempty"` // 被吃的人的方位
}

func (x *S2CChiPaiPush) Reset() {
	*x = S2CChiPaiPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chi_pai_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CChiPaiPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChiPaiPush) ProtoMessage() {}

func (x *S2CChiPaiPush) ProtoReflect() protoreflect.Message {
	mi := &file_chi_pai_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChiPaiPush.ProtoReflect.Descriptor instead.
func (*S2CChiPaiPush) Descriptor() ([]byte, []int) {
	return file_chi_pai_push_proto_rawDescGZIP(), []int{1}
}

func (x *S2CChiPaiPush) GetSeatSeq() int32 {
	if x != nil {
		return x.SeatSeq
	}
	return 0
}

func (x *S2CChiPaiPush) GetCard1() int32 {
	if x != nil {
		return x.Card1
	}
	return 0
}

func (x *S2CChiPaiPush) GetCard2() int32 {
	if x != nil {
		return x.Card2
	}
	return 0
}

func (x *S2CChiPaiPush) GetBeEatCard() int32 {
	if x != nil {
		return x.BeEatCard
	}
	return 0
}

func (x *S2CChiPaiPush) GetBeSeatSeq() int32 {
	if x != nil {
		return x.BeSeatSeq
	}
	return 0
}

var File_chi_pai_push_proto protoreflect.FileDescriptor

var file_chi_pai_push_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x68, 0x69, 0x5f, 0x70, 0x61, 0x69, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x43, 0x68, 0x69, 0x50, 0x61,
	0x69, 0x50, 0x75, 0x73, 0x68, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x43, 0x68, 0x69,
	0x50, 0x61, 0x69, 0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x32, 0x12, 0x1c, 0x0a,
	0x09, 0x42, 0x65, 0x45, 0x61, 0x74, 0x43, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x42, 0x65, 0x45, 0x61, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x42,
	0x65, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x42, 0x65, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0xaa, 0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chi_pai_push_proto_rawDescOnce sync.Once
	file_chi_pai_push_proto_rawDescData = file_chi_pai_push_proto_rawDesc
)

func file_chi_pai_push_proto_rawDescGZIP() []byte {
	file_chi_pai_push_proto_rawDescOnce.Do(func() {
		file_chi_pai_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_chi_pai_push_proto_rawDescData)
	})
	return file_chi_pai_push_proto_rawDescData
}

var file_chi_pai_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chi_pai_push_proto_goTypes = []interface{}{
	(*C2SChiPaiPush)(nil), // 0: C2SChiPaiPush
	(*S2CChiPaiPush)(nil), // 1: S2CChiPaiPush
}
var file_chi_pai_push_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chi_pai_push_proto_init() }
func file_chi_pai_push_proto_init() {
	if File_chi_pai_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chi_pai_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChiPaiPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chi_pai_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CChiPaiPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chi_pai_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chi_pai_push_proto_goTypes,
		DependencyIndexes: file_chi_pai_push_proto_depIdxs,
		MessageInfos:      file_chi_pai_push_proto_msgTypes,
	}.Build()
	File_chi_pai_push_proto = out.File
	file_chi_pai_push_proto_rawDesc = nil
	file_chi_pai_push_proto_goTypes = nil
	file_chi_pai_push_proto_depIdxs = nil
}
