// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                   // 玩家ID
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                  // 玩家昵称
	Gender GENDER `protobuf:"varint,3,opt,name=gender,proto3,enum=GENDER" json:"gender,omitempty"` // 玩家性别 1:男,2:女,3:保密
	Gold   string `protobuf:"bytes,4,opt,name=gold,proto3" json:"gold,omitempty"`                  // 金币数量
	Dia    string `protobuf:"bytes,5,opt,name=dia,proto3" json:"dia,omitempty"`                    // 钻石数量
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetGender() GENDER {
	if x != nil {
		return x.Gender
	}
	return GENDER_GENDER_UNDEFINED
}

func (x *PlayerInfo) GetGold() string {
	if x != nil {
		return x.Gold
	}
	return ""
}

func (x *PlayerInfo) GetDia() string {
	if x != nil {
		return x.Dia
	}
	return ""
}

// 座位信息
type SeatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq int32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // 方位 从0开始 东南西北 （逆时针出牌）
	// uint64 uid = 2; // 玩家ID
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       // 玩家名称
	Gold    string `protobuf:"bytes,3,opt,name=gold,proto3" json:"gold,omitempty"`                       // 玩家金币数量
	XuanQue int32  `protobuf:"varint,4,opt,name=xuan_que,json=xuanQue,proto3" json:"xuan_que,omitempty"` // 选缺, -1 代表未选缺
}

func (x *SeatInfo) Reset() {
	*x = SeatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatInfo) ProtoMessage() {}

func (x *SeatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatInfo.ProtoReflect.Descriptor instead.
func (*SeatInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *SeatInfo) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SeatInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeatInfo) GetGold() string {
	if x != nil {
		return x.Gold
	}
	return ""
}

func (x *SeatInfo) GetXuanQue() int32 {
	if x != nil {
		return x.XuanQue
	}
	return 0
}

// 牌桌信息
type DeskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WanId      WAN_TYPE    `protobuf:"varint,1,opt,name=wan_id,json=wanId,proto3,enum=WAN_TYPE" json:"wan_id,omitempty"`  // 玩法ID （玩法类型）
	ChangCi    int32       `protobuf:"varint,2,opt,name=chang_ci,json=changCi,proto3" json:"chang_ci,omitempty"`          // 场次ID
	CardTotal  int32       `protobuf:"varint,3,opt,name=card_total,json=cardTotal,proto3" json:"card_total,omitempty"`    // 总牌数
	CardRemain int32       `protobuf:"varint,4,opt,name=card_remain,json=cardRemain,proto3" json:"card_remain,omitempty"` // 剩余牌数
	BankerSeq  int32       `protobuf:"varint,5,opt,name=bankerSeq,proto3" json:"bankerSeq,omitempty"`                     // 庄方位 从0开始 东南西北 （逆时针出牌）
	SeatInfos  []*SeatInfo `protobuf:"bytes,6,rep,name=seat_infos,json=seatInfos,proto3" json:"seat_infos,omitempty"`     // 座位信息列表
}

func (x *DeskInfo) Reset() {
	*x = DeskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeskInfo) ProtoMessage() {}

func (x *DeskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeskInfo.ProtoReflect.Descriptor instead.
func (*DeskInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *DeskInfo) GetWanId() WAN_TYPE {
	if x != nil {
		return x.WanId
	}
	return WAN_TYPE_WAN_TYPE_UNDEFINED
}

func (x *DeskInfo) GetChangCi() int32 {
	if x != nil {
		return x.ChangCi
	}
	return 0
}

func (x *DeskInfo) GetCardTotal() int32 {
	if x != nil {
		return x.CardTotal
	}
	return 0
}

func (x *DeskInfo) GetCardRemain() int32 {
	if x != nil {
		return x.CardRemain
	}
	return 0
}

func (x *DeskInfo) GetBankerSeq() int32 {
	if x != nil {
		return x.BankerSeq
	}
	return 0
}

func (x *DeskInfo) GetSeatInfos() []*SeatInfo {
	if x != nil {
		return x.SeatInfos
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x0a,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x07, 0x2e, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x61, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x61, 0x22, 0x5f, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x78, 0x75, 0x61, 0x6e, 0x5f, 0x71, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x78, 0x75, 0x61, 0x6e, 0x51, 0x75, 0x65, 0x22, 0xcf, 0x01, 0x0a, 0x08, 0x44, 0x65, 0x73,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x06, 0x77, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x57, 0x41, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x05, 0x77, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x5f, 0x63, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x43, 0x69, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x52, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x71, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x71,
	0x12, 0x28, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x73, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0xaa, 0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []interface{}{
	(*PlayerInfo)(nil), // 0: PlayerInfo
	(*SeatInfo)(nil),   // 1: SeatInfo
	(*DeskInfo)(nil),   // 2: DeskInfo
	(GENDER)(0),        // 3: GENDER
	(WAN_TYPE)(0),      // 4: WAN_TYPE
}
var file_common_proto_depIdxs = []int32{
	3, // 0: PlayerInfo.gender:type_name -> GENDER
	4, // 1: DeskInfo.wan_id:type_name -> WAN_TYPE
	1, // 2: DeskInfo.seat_infos:type_name -> SeatInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_consts_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
