// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: cfg/consts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息号
type MSG_ID int32

const (
	MSG_ID_HEART MSG_ID = 0 // 心跳
)

// Enum value maps for MSG_ID.
var (
	MSG_ID_name = map[int32]string{
		0: "HEART",
	}
	MSG_ID_value = map[string]int32{
		"HEART": 0,
	}
)

func (x MSG_ID) Enum() *MSG_ID {
	p := new(MSG_ID)
	*p = x
	return p
}

func (x MSG_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_consts_proto_enumTypes[0].Descriptor()
}

func (MSG_ID) Type() protoreflect.EnumType {
	return &file_cfg_consts_proto_enumTypes[0]
}

func (x MSG_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_ID.Descriptor instead.
func (MSG_ID) EnumDescriptor() ([]byte, []int) {
	return file_cfg_consts_proto_rawDescGZIP(), []int{0}
}

var File_cfg_consts_proto protoreflect.FileDescriptor

var file_cfg_consts_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x66, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x13, 0x0a, 0x06, 0x4d, 0x53, 0x47, 0x5f, 0x49, 0x44, 0x12, 0x09, 0x0a, 0x05,
	0x48, 0x45, 0x41, 0x52, 0x54, 0x10, 0x00, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0xaa,
	0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cfg_consts_proto_rawDescOnce sync.Once
	file_cfg_consts_proto_rawDescData = file_cfg_consts_proto_rawDesc
)

func file_cfg_consts_proto_rawDescGZIP() []byte {
	file_cfg_consts_proto_rawDescOnce.Do(func() {
		file_cfg_consts_proto_rawDescData = protoimpl.X.CompressGZIP(file_cfg_consts_proto_rawDescData)
	})
	return file_cfg_consts_proto_rawDescData
}

var file_cfg_consts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cfg_consts_proto_goTypes = []interface{}{
	(MSG_ID)(0), // 0: MSG_ID
}
var file_cfg_consts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cfg_consts_proto_init() }
func file_cfg_consts_proto_init() {
	if File_cfg_consts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cfg_consts_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cfg_consts_proto_goTypes,
		DependencyIndexes: file_cfg_consts_proto_depIdxs,
		EnumInfos:         file_cfg_consts_proto_enumTypes,
	}.Build()
	File_cfg_consts_proto = out.File
	file_cfg_consts_proto_rawDesc = nil
	file_cfg_consts_proto_goTypes = nil
	file_cfg_consts_proto_depIdxs = nil
}
