// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: game_end_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 封顶标签
type WIN_MAX_LIMIT_TYPE int32

const (
	WIN_MAX_LIMIT_TYPE_NONE     WIN_MAX_LIMIT_TYPE = 0 // 没有
	WIN_MAX_LIMIT_TYPE_MUL      WIN_MAX_LIMIT_TYPE = 1 // 倍数
	WIN_MAX_LIMIT_TYPE_BANKRUPT WIN_MAX_LIMIT_TYPE = 2 // 破产
)

// Enum value maps for WIN_MAX_LIMIT_TYPE.
var (
	WIN_MAX_LIMIT_TYPE_name = map[int32]string{
		0: "NONE",
		1: "MUL",
		2: "BANKRUPT",
	}
	WIN_MAX_LIMIT_TYPE_value = map[string]int32{
		"NONE":     0,
		"MUL":      1,
		"BANKRUPT": 2,
	}
)

func (x WIN_MAX_LIMIT_TYPE) Enum() *WIN_MAX_LIMIT_TYPE {
	p := new(WIN_MAX_LIMIT_TYPE)
	*p = x
	return p
}

func (x WIN_MAX_LIMIT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WIN_MAX_LIMIT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_game_end_push_proto_enumTypes[0].Descriptor()
}

func (WIN_MAX_LIMIT_TYPE) Type() protoreflect.EnumType {
	return &file_game_end_push_proto_enumTypes[0]
}

func (x WIN_MAX_LIMIT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WIN_MAX_LIMIT_TYPE.Descriptor instead.
func (WIN_MAX_LIMIT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_game_end_push_proto_rawDescGZIP(), []int{0}
}

type S2CGameEndPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfoList []*GameEndPlayerInfo `protobuf:"bytes,1,rep,name=PlayerInfoList,proto3" json:"PlayerInfoList,omitempty"`
	Record         []*GameRecord        `protobuf:"bytes,2,rep,name=Record,proto3" json:"Record,omitempty"`
}

func (x *S2CGameEndPush) Reset() {
	*x = S2CGameEndPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_end_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGameEndPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGameEndPush) ProtoMessage() {}

func (x *S2CGameEndPush) ProtoReflect() protoreflect.Message {
	mi := &file_game_end_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGameEndPush.ProtoReflect.Descriptor instead.
func (*S2CGameEndPush) Descriptor() ([]byte, []int) {
	return file_game_end_push_proto_rawDescGZIP(), []int{0}
}

func (x *S2CGameEndPush) GetPlayerInfoList() []*GameEndPlayerInfo {
	if x != nil {
		return x.PlayerInfoList
	}
	return nil
}

func (x *S2CGameEndPush) GetRecord() []*GameRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type C2SGameEndPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGameEndPush) Reset() {
	*x = C2SGameEndPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_end_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGameEndPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGameEndPush) ProtoMessage() {}

func (x *C2SGameEndPush) ProtoReflect() protoreflect.Message {
	mi := &file_game_end_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGameEndPush.ProtoReflect.Descriptor instead.
func (*C2SGameEndPush) Descriptor() ([]byte, []int) {
	return file_game_end_push_proto_rawDescGZIP(), []int{1}
}

type GameRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinSeatId      int32              `protobuf:"varint,1,opt,name=winSeatId,proto3" json:"winSeatId,omitempty"`                                   // 赢得位置
	LoseSeatId     int32              `protobuf:"varint,2,opt,name=loseSeatId,proto3" json:"loseSeatId,omitempty"`                                 // 输的位置
	WinMulti       int32              `protobuf:"varint,3,opt,name=winMulti,proto3" json:"winMulti,omitempty"`                                     // 赢牌倍率
	WinCoin        string             `protobuf:"bytes,4,opt,name=winCoin,proto3" json:"winCoin,omitempty"`                                        // 赢取的金币
	WinType        int32              `protobuf:"varint,5,opt,name=winType,proto3" json:"winType,omitempty"`                                       // 赢的类型
	MaxWinLimitTag WIN_MAX_LIMIT_TYPE `protobuf:"varint,6,opt,name=maxWinLimitTag,proto3,enum=WIN_MAX_LIMIT_TYPE" json:"maxWinLimitTag,omitempty"` // 封顶标签
	WinCardTypes   []int32            `protobuf:"varint,7,rep,packed,name=winCardTypes,proto3" json:"winCardTypes,omitempty"`                      // 赢取牌型
}

func (x *GameRecord) Reset() {
	*x = GameRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_end_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRecord) ProtoMessage() {}

func (x *GameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_game_end_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRecord.ProtoReflect.Descriptor instead.
func (*GameRecord) Descriptor() ([]byte, []int) {
	return file_game_end_push_proto_rawDescGZIP(), []int{2}
}

func (x *GameRecord) GetWinSeatId() int32 {
	if x != nil {
		return x.WinSeatId
	}
	return 0
}

func (x *GameRecord) GetLoseSeatId() int32 {
	if x != nil {
		return x.LoseSeatId
	}
	return 0
}

func (x *GameRecord) GetWinMulti() int32 {
	if x != nil {
		return x.WinMulti
	}
	return 0
}

func (x *GameRecord) GetWinCoin() string {
	if x != nil {
		return x.WinCoin
	}
	return ""
}

func (x *GameRecord) GetWinType() int32 {
	if x != nil {
		return x.WinType
	}
	return 0
}

func (x *GameRecord) GetMaxWinLimitTag() WIN_MAX_LIMIT_TYPE {
	if x != nil {
		return x.MaxWinLimitTag
	}
	return WIN_MAX_LIMIT_TYPE_NONE
}

func (x *GameRecord) GetWinCardTypes() []int32 {
	if x != nil {
		return x.WinCardTypes
	}
	return nil
}

type GameEndPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid             uint64             `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                 // 唯一ID
	SeatId          int32              `protobuf:"varint,2,opt,name=seatId,proto3" json:"seatId,omitempty"`                                           // 座位ID
	WinLossCoin     string             `protobuf:"bytes,3,opt,name=winLossCoin,proto3" json:"winLossCoin,omitempty"`                                  // 输赢的钱数，带正负
	Coin            string             `protobuf:"bytes,4,opt,name=coin,proto3" json:"coin,omitempty"`                                                // 最后的钱
	HandCards       []int32            `protobuf:"varint,5,rep,packed,name=handCards,proto3" json:"handCards,omitempty"`                              // 手牌
	CardTotalMul    int32              `protobuf:"varint,6,opt,name=cardTotalMul,proto3" json:"cardTotalMul,omitempty"`                               // 牌型总倍数
	HuTotalCount    int32              `protobuf:"varint,7,opt,name=huTotalCount,proto3" json:"huTotalCount,omitempty"`                               // 总胡次数
	MaxScoreMul     int32              `protobuf:"varint,8,opt,name=maxScoreMul,proto3" json:"maxScoreMul,omitempty"`                                 // 封顶倍数
	MaxScoreMulType WIN_MAX_LIMIT_TYPE `protobuf:"varint,9,opt,name=maxScoreMulType,proto3,enum=WIN_MAX_LIMIT_TYPE" json:"maxScoreMulType,omitempty"` // 封顶类型
}

func (x *GameEndPlayerInfo) Reset() {
	*x = GameEndPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_end_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEndPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEndPlayerInfo) ProtoMessage() {}

func (x *GameEndPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_end_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEndPlayerInfo.ProtoReflect.Descriptor instead.
func (*GameEndPlayerInfo) Descriptor() ([]byte, []int) {
	return file_game_end_push_proto_rawDescGZIP(), []int{3}
}

func (x *GameEndPlayerInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GameEndPlayerInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *GameEndPlayerInfo) GetWinLossCoin() string {
	if x != nil {
		return x.WinLossCoin
	}
	return ""
}

func (x *GameEndPlayerInfo) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *GameEndPlayerInfo) GetHandCards() []int32 {
	if x != nil {
		return x.HandCards
	}
	return nil
}

func (x *GameEndPlayerInfo) GetCardTotalMul() int32 {
	if x != nil {
		return x.CardTotalMul
	}
	return 0
}

func (x *GameEndPlayerInfo) GetHuTotalCount() int32 {
	if x != nil {
		return x.HuTotalCount
	}
	return 0
}

func (x *GameEndPlayerInfo) GetMaxScoreMul() int32 {
	if x != nil {
		return x.MaxScoreMul
	}
	return 0
}

func (x *GameEndPlayerInfo) GetMaxScoreMulType() WIN_MAX_LIMIT_TYPE {
	if x != nil {
		return x.MaxScoreMulType
	}
	return WIN_MAX_LIMIT_TYPE_NONE
}

var File_game_end_push_proto protoreflect.FileDescriptor

var file_game_end_push_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x47, 0x61, 0x6d, 0x65,
	0x45, 0x6e, 0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x3a, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x50, 0x75, 0x73, 0x68, 0x22, 0xfb, 0x01, 0x0a, 0x0a, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x69, 0x6e,
	0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x69,
	0x6e, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x73, 0x65, 0x53,
	0x65, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x6f, 0x73,
	0x65, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x77, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x77, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x57, 0x69,
	0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x54, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x57, 0x49, 0x4e, 0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x57, 0x69, 0x6e, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x54, 0x61, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x77, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x77, 0x69, 0x6e, 0x43,
	0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0xba, 0x02, 0x0a, 0x11, 0x47, 0x61, 0x6d,
	0x65, 0x45, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x69, 0x6e, 0x4c,
	0x6f, 0x73, 0x73, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77,
	0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x73, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x61, 0x72, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x75, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x75, 0x6c,
	0x12, 0x22, 0x0a, 0x0c, 0x68, 0x75, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x68, 0x75, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x4d, 0x75, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x4d, 0x75, 0x6c, 0x12, 0x3d, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x4d, 0x75, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x57, 0x49, 0x4e, 0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x52, 0x0f, 0x6d, 0x61, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x75,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x35, 0x0a, 0x12, 0x57, 0x49, 0x4e, 0x5f, 0x4d, 0x41, 0x58,
	0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x55, 0x4c, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x42, 0x41, 0x4e, 0x4b, 0x52, 0x55, 0x50, 0x54, 0x10, 0x02, 0x42, 0x0b, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0xaa, 0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_game_end_push_proto_rawDescOnce sync.Once
	file_game_end_push_proto_rawDescData = file_game_end_push_proto_rawDesc
)

func file_game_end_push_proto_rawDescGZIP() []byte {
	file_game_end_push_proto_rawDescOnce.Do(func() {
		file_game_end_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_end_push_proto_rawDescData)
	})
	return file_game_end_push_proto_rawDescData
}

var file_game_end_push_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_end_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_game_end_push_proto_goTypes = []interface{}{
	(WIN_MAX_LIMIT_TYPE)(0),   // 0: WIN_MAX_LIMIT_TYPE
	(*S2CGameEndPush)(nil),    // 1: S2CGameEndPush
	(*C2SGameEndPush)(nil),    // 2: C2SGameEndPush
	(*GameRecord)(nil),        // 3: GameRecord
	(*GameEndPlayerInfo)(nil), // 4: GameEndPlayerInfo
}
var file_game_end_push_proto_depIdxs = []int32{
	4, // 0: S2CGameEndPush.PlayerInfoList:type_name -> GameEndPlayerInfo
	3, // 1: S2CGameEndPush.Record:type_name -> GameRecord
	0, // 2: GameRecord.maxWinLimitTag:type_name -> WIN_MAX_LIMIT_TYPE
	0, // 3: GameEndPlayerInfo.maxScoreMulType:type_name -> WIN_MAX_LIMIT_TYPE
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_end_push_proto_init() }
func file_game_end_push_proto_init() {
	if File_game_end_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_end_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGameEndPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_end_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGameEndPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_end_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_end_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEndPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_end_push_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_end_push_proto_goTypes,
		DependencyIndexes: file_game_end_push_proto_depIdxs,
		EnumInfos:         file_game_end_push_proto_enumTypes,
		MessageInfos:      file_game_end_push_proto_msgTypes,
	}.Build()
	File_game_end_push_proto = out.File
	file_game_end_push_proto_rawDesc = nil
	file_game_end_push_proto_goTypes = nil
	file_game_end_push_proto_depIdxs = nil
}
