// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: gang_pai_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 玩家杠牌 推送
type C2SGangPaiPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatSeq   int32     `protobuf:"varint,1,opt,name=SeatSeq,proto3" json:"SeatSeq,omitempty"`          // 杠牌的玩家座位方位
	Card      int32     `protobuf:"varint,2,opt,name=Card,proto3" json:"Card,omitempty"`                // 杠牌的牌
	Type      GANG_TYPE `protobuf:"varint,3,opt,name=Type,proto3,enum=GANG_TYPE" json:"Type,omitempty"` // 杠的类型
	BeSeatSeq int32     `protobuf:"varint,4,opt,name=BeSeatSeq,proto3" json:"BeSeatSeq,omitempty"`      // 被杠牌的人的座位方位 -1 代表
}

func (x *C2SGangPaiPush) Reset() {
	*x = C2SGangPaiPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gang_pai_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGangPaiPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGangPaiPush) ProtoMessage() {}

func (x *C2SGangPaiPush) ProtoReflect() protoreflect.Message {
	mi := &file_gang_pai_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGangPaiPush.ProtoReflect.Descriptor instead.
func (*C2SGangPaiPush) Descriptor() ([]byte, []int) {
	return file_gang_pai_push_proto_rawDescGZIP(), []int{0}
}

func (x *C2SGangPaiPush) GetSeatSeq() int32 {
	if x != nil {
		return x.SeatSeq
	}
	return 0
}

func (x *C2SGangPaiPush) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

func (x *C2SGangPaiPush) GetType() GANG_TYPE {
	if x != nil {
		return x.Type
	}
	return GANG_TYPE_GANG_TYPE_NONE
}

func (x *C2SGangPaiPush) GetBeSeatSeq() int32 {
	if x != nil {
		return x.BeSeatSeq
	}
	return 0
}

// S -> C 玩家杠牌 推送
type S2CGangPaiPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []int32 `protobuf:"varint,1,rep,packed,name=cards,proto3" json:"cards,omitempty"` // 自己的牌
}

func (x *S2CGangPaiPush) Reset() {
	*x = S2CGangPaiPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gang_pai_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGangPaiPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGangPaiPush) ProtoMessage() {}

func (x *S2CGangPaiPush) ProtoReflect() protoreflect.Message {
	mi := &file_gang_pai_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGangPaiPush.ProtoReflect.Descriptor instead.
func (*S2CGangPaiPush) Descriptor() ([]byte, []int) {
	return file_gang_pai_push_proto_rawDescGZIP(), []int{1}
}

func (x *S2CGangPaiPush) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_gang_pai_push_proto protoreflect.FileDescriptor

var file_gang_pai_push_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x61, 0x6e, 0x67, 0x5f, 0x70, 0x61, 0x69, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x47, 0x61, 0x6e, 0x67, 0x50, 0x61,
	0x69, 0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0a, 0x2e, 0x47, 0x41, 0x4e, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x65, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x42, 0x65, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65,
	0x71, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x47, 0x61, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x50,
	0x75, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0xaa, 0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gang_pai_push_proto_rawDescOnce sync.Once
	file_gang_pai_push_proto_rawDescData = file_gang_pai_push_proto_rawDesc
)

func file_gang_pai_push_proto_rawDescGZIP() []byte {
	file_gang_pai_push_proto_rawDescOnce.Do(func() {
		file_gang_pai_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_gang_pai_push_proto_rawDescData)
	})
	return file_gang_pai_push_proto_rawDescData
}

var file_gang_pai_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gang_pai_push_proto_goTypes = []interface{}{
	(*C2SGangPaiPush)(nil), // 0: C2SGangPaiPush
	(*S2CGangPaiPush)(nil), // 1: S2CGangPaiPush
	(GANG_TYPE)(0),         // 2: GANG_TYPE
}
var file_gang_pai_push_proto_depIdxs = []int32{
	2, // 0: C2SGangPaiPush.Type:type_name -> GANG_TYPE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gang_pai_push_proto_init() }
func file_gang_pai_push_proto_init() {
	if File_gang_pai_push_proto != nil {
		return
	}
	file_consts_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gang_pai_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGangPaiPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gang_pai_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGangPaiPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gang_pai_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gang_pai_push_proto_goTypes,
		DependencyIndexes: file_gang_pai_push_proto_depIdxs,
		MessageInfos:      file_gang_pai_push_proto_msgTypes,
	}.Build()
	File_gang_pai_push_proto = out.File
	file_gang_pai_push_proto_rawDesc = nil
	file_gang_pai_push_proto_goTypes = nil
	file_gang_pai_push_proto_depIdxs = nil
}
