// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: gang_end_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 杠牌结算推送
type C2SGangEndPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGangEndPush) Reset() {
	*x = C2SGangEndPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gang_end_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGangEndPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGangEndPush) ProtoMessage() {}

func (x *C2SGangEndPush) ProtoReflect() protoreflect.Message {
	mi := &file_gang_end_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGangEndPush.ProtoReflect.Descriptor instead.
func (*C2SGangEndPush) Descriptor() ([]byte, []int) {
	return file_gang_end_push_proto_rawDescGZIP(), []int{0}
}

// S -> C 杠牌结算推送
type S2CGangEndPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatSeq     int32          `protobuf:"varint,1,opt,name=SeatSeq,proto3" json:"SeatSeq,omitempty"`          // 座位方位
	Card        int32          `protobuf:"varint,2,opt,name=Card,proto3" json:"Card,omitempty"`                // 杠的牌
	Type        GANG_TYPE      `protobuf:"varint,3,opt,name=Type,proto3,enum=GANG_TYPE" json:"Type,omitempty"` // 杠的类型
	WinLossList []*GangWinLoss `protobuf:"bytes,4,rep,name=WinLossList,proto3" json:"WinLossList,omitempty"`   // 玩家输赢列表
}

func (x *S2CGangEndPush) Reset() {
	*x = S2CGangEndPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gang_end_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGangEndPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGangEndPush) ProtoMessage() {}

func (x *S2CGangEndPush) ProtoReflect() protoreflect.Message {
	mi := &file_gang_end_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGangEndPush.ProtoReflect.Descriptor instead.
func (*S2CGangEndPush) Descriptor() ([]byte, []int) {
	return file_gang_end_push_proto_rawDescGZIP(), []int{1}
}

func (x *S2CGangEndPush) GetSeatSeq() int32 {
	if x != nil {
		return x.SeatSeq
	}
	return 0
}

func (x *S2CGangEndPush) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

func (x *S2CGangEndPush) GetType() GANG_TYPE {
	if x != nil {
		return x.Type
	}
	return GANG_TYPE_GANG_TYPE_NONE
}

func (x *S2CGangEndPush) GetWinLossList() []*GangWinLoss {
	if x != nil {
		return x.WinLossList
	}
	return nil
}

// 方位输赢
type GangWinLoss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatSeq int32  `protobuf:"varint,1,opt,name=SeatSeq,proto3" json:"SeatSeq,omitempty"` // 座位方位
	WinLoss string `protobuf:"bytes,2,opt,name=WinLoss,proto3" json:"WinLoss,omitempty"`  // 输赢金币数量
}

func (x *GangWinLoss) Reset() {
	*x = GangWinLoss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gang_end_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GangWinLoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GangWinLoss) ProtoMessage() {}

func (x *GangWinLoss) ProtoReflect() protoreflect.Message {
	mi := &file_gang_end_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GangWinLoss.ProtoReflect.Descriptor instead.
func (*GangWinLoss) Descriptor() ([]byte, []int) {
	return file_gang_end_push_proto_rawDescGZIP(), []int{2}
}

func (x *GangWinLoss) GetSeatSeq() int32 {
	if x != nil {
		return x.SeatSeq
	}
	return 0
}

func (x *GangWinLoss) GetWinLoss() string {
	if x != nil {
		return x.WinLoss
	}
	return ""
}

var File_gang_end_push_proto protoreflect.FileDescriptor

var file_gang_end_push_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x61, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x47, 0x61, 0x6e, 0x67, 0x45, 0x6e,
	0x64, 0x50, 0x75, 0x73, 0x68, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x47, 0x61, 0x6e,
	0x67, 0x45, 0x6e, 0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74,
	0x53, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x47, 0x41, 0x4e, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x47, 0x61,
	0x6e, 0x67, 0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x0b, 0x57, 0x69, 0x6e, 0x4c, 0x6f,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x0b, 0x47, 0x61, 0x6e, 0x67, 0x57, 0x69,
	0x6e, 0x4c, 0x6f, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x73, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0xaa, 0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gang_end_push_proto_rawDescOnce sync.Once
	file_gang_end_push_proto_rawDescData = file_gang_end_push_proto_rawDesc
)

func file_gang_end_push_proto_rawDescGZIP() []byte {
	file_gang_end_push_proto_rawDescOnce.Do(func() {
		file_gang_end_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_gang_end_push_proto_rawDescData)
	})
	return file_gang_end_push_proto_rawDescData
}

var file_gang_end_push_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gang_end_push_proto_goTypes = []interface{}{
	(*C2SGangEndPush)(nil), // 0: C2SGangEndPush
	(*S2CGangEndPush)(nil), // 1: S2CGangEndPush
	(*GangWinLoss)(nil),    // 2: GangWinLoss
	(GANG_TYPE)(0),         // 3: GANG_TYPE
}
var file_gang_end_push_proto_depIdxs = []int32{
	3, // 0: S2CGangEndPush.Type:type_name -> GANG_TYPE
	2, // 1: S2CGangEndPush.WinLossList:type_name -> GangWinLoss
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gang_end_push_proto_init() }
func file_gang_end_push_proto_init() {
	if File_gang_end_push_proto != nil {
		return
	}
	file_consts_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gang_end_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGangEndPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gang_end_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGangEndPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gang_end_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GangWinLoss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gang_end_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gang_end_push_proto_goTypes,
		DependencyIndexes: file_gang_end_push_proto_depIdxs,
		MessageInfos:      file_gang_end_push_proto_msgTypes,
	}.Build()
	File_gang_end_push_proto = out.File
	file_gang_end_push_proto_rawDesc = nil
	file_gang_end_push_proto_goTypes = nil
	file_gang_end_push_proto_depIdxs = nil
}
