// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: cfg/heart.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 心跳消息 CLIENT_Heart
type C2SHeart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SHeart) Reset() {
	*x = C2SHeart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_heart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SHeart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHeart) ProtoMessage() {}

func (x *C2SHeart) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_heart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHeart.ProtoReflect.Descriptor instead.
func (*C2SHeart) Descriptor() ([]byte, []int) {
	return file_cfg_heart_proto_rawDescGZIP(), []int{0}
}

// S -> C 心跳消息 SERVER_Heart
type S2CHeart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"` // 毫秒级别时间戳
}

func (x *S2CHeart) Reset() {
	*x = S2CHeart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_heart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CHeart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHeart) ProtoMessage() {}

func (x *S2CHeart) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_heart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHeart.ProtoReflect.Descriptor instead.
func (*S2CHeart) Descriptor() ([]byte, []int) {
	return file_cfg_heart_proto_rawDescGZIP(), []int{1}
}

func (x *S2CHeart) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_cfg_heart_proto protoreflect.FileDescriptor

var file_cfg_heart_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x66, 0x67, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x0a, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x48, 0x65, 0x61, 0x72, 0x74, 0x22, 0x28, 0x0a,
	0x08, 0x53, 0x32, 0x43, 0x48, 0x65, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0xaa,
	0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cfg_heart_proto_rawDescOnce sync.Once
	file_cfg_heart_proto_rawDescData = file_cfg_heart_proto_rawDesc
)

func file_cfg_heart_proto_rawDescGZIP() []byte {
	file_cfg_heart_proto_rawDescOnce.Do(func() {
		file_cfg_heart_proto_rawDescData = protoimpl.X.CompressGZIP(file_cfg_heart_proto_rawDescData)
	})
	return file_cfg_heart_proto_rawDescData
}

var file_cfg_heart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cfg_heart_proto_goTypes = []interface{}{
	(*C2SHeart)(nil), // 0: C2SHeart
	(*S2CHeart)(nil), // 1: S2CHeart
}
var file_cfg_heart_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cfg_heart_proto_init() }
func file_cfg_heart_proto_init() {
	if File_cfg_heart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cfg_heart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SHeart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_heart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CHeart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cfg_heart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cfg_heart_proto_goTypes,
		DependencyIndexes: file_cfg_heart_proto_depIdxs,
		MessageInfos:      file_cfg_heart_proto_msgTypes,
	}.Build()
	File_cfg_heart_proto = out.File
	file_cfg_heart_proto_rawDesc = nil
	file_cfg_heart_proto_goTypes = nil
	file_cfg_heart_proto_depIdxs = nil
}
