// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: main_wan_info.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 主玩法信息
type C2SMainWanInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SMainWanInfo) Reset() {
	*x = C2SMainWanInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_wan_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SMainWanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMainWanInfo) ProtoMessage() {}

func (x *C2SMainWanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_main_wan_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMainWanInfo.ProtoReflect.Descriptor instead.
func (*C2SMainWanInfo) Descriptor() ([]byte, []int) {
	return file_main_wan_info_proto_rawDescGZIP(), []int{0}
}

// 主玩法信息定义
type MainWanInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`     // 玩法ID
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // 标题名称
	Sort uint32 `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"` // 序号
}

func (x *MainWanInfo) Reset() {
	*x = MainWanInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_wan_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MainWanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainWanInfo) ProtoMessage() {}

func (x *MainWanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_main_wan_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainWanInfo.ProtoReflect.Descriptor instead.
func (*MainWanInfo) Descriptor() ([]byte, []int) {
	return file_main_wan_info_proto_rawDescGZIP(), []int{1}
}

func (x *MainWanInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MainWanInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MainWanInfo) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// S -> C 主玩法信息
type S2CMainWanInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WanInfos []*MainWanInfo `protobuf:"bytes,1,rep,name=wanInfos,proto3" json:"wanInfos,omitempty"` // 主玩法列表
}

func (x *S2CMainWanInfo) Reset() {
	*x = S2CMainWanInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_wan_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMainWanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMainWanInfo) ProtoMessage() {}

func (x *S2CMainWanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_main_wan_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMainWanInfo.ProtoReflect.Descriptor instead.
func (*S2CMainWanInfo) Descriptor() ([]byte, []int) {
	return file_main_wan_info_proto_rawDescGZIP(), []int{2}
}

func (x *S2CMainWanInfo) GetWanInfos() []*MainWanInfo {
	if x != nil {
		return x.WanInfos
	}
	return nil
}

var File_main_wan_info_proto protoreflect.FileDescriptor

var file_main_wan_info_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x77, 0x61, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x4d, 0x61, 0x69, 0x6e,
	0x57, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x45, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x57,
	0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x3a,
	0x0a, 0x0e, 0x53, 0x32, 0x43, 0x4d, 0x61, 0x69, 0x6e, 0x57, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x28, 0x0a, 0x08, 0x77, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x57, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x77, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x42, 0x11, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0xaa, 0x02, 0x08, 0x70, 0x62, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_main_wan_info_proto_rawDescOnce sync.Once
	file_main_wan_info_proto_rawDescData = file_main_wan_info_proto_rawDesc
)

func file_main_wan_info_proto_rawDescGZIP() []byte {
	file_main_wan_info_proto_rawDescOnce.Do(func() {
		file_main_wan_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_main_wan_info_proto_rawDescData)
	})
	return file_main_wan_info_proto_rawDescData
}

var file_main_wan_info_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_main_wan_info_proto_goTypes = []interface{}{
	(*C2SMainWanInfo)(nil), // 0: C2SMainWanInfo
	(*MainWanInfo)(nil),    // 1: MainWanInfo
	(*S2CMainWanInfo)(nil), // 2: S2CMainWanInfo
}
var file_main_wan_info_proto_depIdxs = []int32{
	1, // 0: S2CMainWanInfo.wanInfos:type_name -> MainWanInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_main_wan_info_proto_init() }
func file_main_wan_info_proto_init() {
	if File_main_wan_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_main_wan_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SMainWanInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_wan_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MainWanInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_wan_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMainWanInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_main_wan_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_main_wan_info_proto_goTypes,
		DependencyIndexes: file_main_wan_info_proto_depIdxs,
		MessageInfos:      file_main_wan_info_proto_msgTypes,
	}.Build()
	File_main_wan_info_proto = out.File
	file_main_wan_info_proto_rawDesc = nil
	file_main_wan_info_proto_goTypes = nil
	file_main_wan_info_proto_depIdxs = nil
}
