// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: mo_pai_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 通知玩家摸牌 推送
type C2SMoPaiPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SMoPaiPush) Reset() {
	*x = C2SMoPaiPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mo_pai_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SMoPaiPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMoPaiPush) ProtoMessage() {}

func (x *C2SMoPaiPush) ProtoReflect() protoreflect.Message {
	mi := &file_mo_pai_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMoPaiPush.ProtoReflect.Descriptor instead.
func (*C2SMoPaiPush) Descriptor() ([]byte, []int) {
	return file_mo_pai_push_proto_rawDescGZIP(), []int{0}
}

// S -> C 通知玩家摸牌 推送
type S2CMoPaiPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatSeq     int32 `protobuf:"varint,1,opt,name=SeatSeq,proto3" json:"SeatSeq,omitempty"`         // 座位方位
	Card        int32 `protobuf:"varint,2,opt,name=Card,proto3" json:"Card,omitempty"`               // 摸到的牌
	IsAfterGang bool  `protobuf:"varint,3,opt,name=IsAfterGang,proto3" json:"IsAfterGang,omitempty"` // 是否为杠后摸牌
}

func (x *S2CMoPaiPush) Reset() {
	*x = S2CMoPaiPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mo_pai_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CMoPaiPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMoPaiPush) ProtoMessage() {}

func (x *S2CMoPaiPush) ProtoReflect() protoreflect.Message {
	mi := &file_mo_pai_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMoPaiPush.ProtoReflect.Descriptor instead.
func (*S2CMoPaiPush) Descriptor() ([]byte, []int) {
	return file_mo_pai_push_proto_rawDescGZIP(), []int{1}
}

func (x *S2CMoPaiPush) GetSeatSeq() int32 {
	if x != nil {
		return x.SeatSeq
	}
	return 0
}

func (x *S2CMoPaiPush) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

func (x *S2CMoPaiPush) GetIsAfterGang() bool {
	if x != nil {
		return x.IsAfterGang
	}
	return false
}

var File_mo_pai_push_proto protoreflect.FileDescriptor

var file_mo_pai_push_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x6f, 0x5f, 0x70, 0x61, 0x69, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x4d, 0x6f, 0x50, 0x61, 0x69, 0x50,
	0x75, 0x73, 0x68, 0x22, 0x5e, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x4d, 0x6f, 0x50, 0x61, 0x69, 0x50,
	0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x65, 0x61, 0x74, 0x53, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x41, 0x66, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x41, 0x66, 0x74, 0x65, 0x72, 0x47,
	0x61, 0x6e, 0x67, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0xaa, 0x02, 0x02, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mo_pai_push_proto_rawDescOnce sync.Once
	file_mo_pai_push_proto_rawDescData = file_mo_pai_push_proto_rawDesc
)

func file_mo_pai_push_proto_rawDescGZIP() []byte {
	file_mo_pai_push_proto_rawDescOnce.Do(func() {
		file_mo_pai_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_mo_pai_push_proto_rawDescData)
	})
	return file_mo_pai_push_proto_rawDescData
}

var file_mo_pai_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mo_pai_push_proto_goTypes = []interface{}{
	(*C2SMoPaiPush)(nil), // 0: C2SMoPaiPush
	(*S2CMoPaiPush)(nil), // 1: S2CMoPaiPush
}
var file_mo_pai_push_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mo_pai_push_proto_init() }
func file_mo_pai_push_proto_init() {
	if File_mo_pai_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mo_pai_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SMoPaiPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mo_pai_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CMoPaiPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mo_pai_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mo_pai_push_proto_goTypes,
		DependencyIndexes: file_mo_pai_push_proto_depIdxs,
		MessageInfos:      file_mo_pai_push_proto_msgTypes,
	}.Build()
	File_mo_pai_push_proto = out.File
	file_mo_pai_push_proto_rawDesc = nil
	file_mo_pai_push_proto_goTypes = nil
	file_mo_pai_push_proto_depIdxs = nil
}
