// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: other_win_loss_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S  推送
type C2SOtherWinLossPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hold int32 `protobuf:"varint,1,opt,name=hold,proto3" json:"hold,omitempty"` // 前端透传 保留 前端要求，合理性前端提供
	Card int32 `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"` // 杠的牌
}

func (x *C2SOtherWinLossPush) Reset() {
	*x = C2SOtherWinLossPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_win_loss_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SOtherWinLossPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SOtherWinLossPush) ProtoMessage() {}

func (x *C2SOtherWinLossPush) ProtoReflect() protoreflect.Message {
	mi := &file_other_win_loss_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SOtherWinLossPush.ProtoReflect.Descriptor instead.
func (*C2SOtherWinLossPush) Descriptor() ([]byte, []int) {
	return file_other_win_loss_push_proto_rawDescGZIP(), []int{0}
}

func (x *C2SOtherWinLossPush) GetHold() int32 {
	if x != nil {
		return x.Hold
	}
	return 0
}

func (x *C2SOtherWinLossPush) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

// S -> C  推送
type S2COtherWinLossPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hold int32 `protobuf:"varint,1,opt,name=hold,proto3" json:"hold,omitempty"` // 前端透传 保留 前端要求，合理性前端提供
}

func (x *S2COtherWinLossPush) Reset() {
	*x = S2COtherWinLossPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_win_loss_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2COtherWinLossPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2COtherWinLossPush) ProtoMessage() {}

func (x *S2COtherWinLossPush) ProtoReflect() protoreflect.Message {
	mi := &file_other_win_loss_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2COtherWinLossPush.ProtoReflect.Descriptor instead.
func (*S2COtherWinLossPush) Descriptor() ([]byte, []int) {
	return file_other_win_loss_push_proto_rawDescGZIP(), []int{1}
}

func (x *S2COtherWinLossPush) GetHold() int32 {
	if x != nil {
		return x.Hold
	}
	return 0
}

var File_other_win_loss_push_proto protoreflect.FileDescriptor

var file_other_win_loss_push_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x77, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x73, 0x73,
	0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x13, 0x43,
	0x32, 0x53, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x73, 0x50, 0x75,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x53, 0x32,
	0x43, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x73, 0x50, 0x75, 0x73,
	0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x68, 0x6f, 0x6c, 0x64, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0xaa, 0x02, 0x02,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_other_win_loss_push_proto_rawDescOnce sync.Once
	file_other_win_loss_push_proto_rawDescData = file_other_win_loss_push_proto_rawDesc
)

func file_other_win_loss_push_proto_rawDescGZIP() []byte {
	file_other_win_loss_push_proto_rawDescOnce.Do(func() {
		file_other_win_loss_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_other_win_loss_push_proto_rawDescData)
	})
	return file_other_win_loss_push_proto_rawDescData
}

var file_other_win_loss_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_other_win_loss_push_proto_goTypes = []interface{}{
	(*C2SOtherWinLossPush)(nil), // 0: C2SOtherWinLossPush
	(*S2COtherWinLossPush)(nil), // 1: S2COtherWinLossPush
}
var file_other_win_loss_push_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_other_win_loss_push_proto_init() }
func file_other_win_loss_push_proto_init() {
	if File_other_win_loss_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_other_win_loss_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SOtherWinLossPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_win_loss_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2COtherWinLossPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_other_win_loss_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_other_win_loss_push_proto_goTypes,
		DependencyIndexes: file_other_win_loss_push_proto_depIdxs,
		MessageInfos:      file_other_win_loss_push_proto_msgTypes,
	}.Build()
	File_other_win_loss_push_proto = out.File
	file_other_win_loss_push_proto_rawDesc = nil
	file_other_win_loss_push_proto_goTypes = nil
	file_other_win_loss_push_proto_depIdxs = nil
}
