// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: sync_player_info_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 同步玩家信息
type C2SSyncPlayerInfoPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SSyncPlayerInfoPush) Reset() {
	*x = C2SSyncPlayerInfoPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_player_info_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SSyncPlayerInfoPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSyncPlayerInfoPush) ProtoMessage() {}

func (x *C2SSyncPlayerInfoPush) ProtoReflect() protoreflect.Message {
	mi := &file_sync_player_info_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSyncPlayerInfoPush.ProtoReflect.Descriptor instead.
func (*C2SSyncPlayerInfoPush) Descriptor() ([]byte, []int) {
	return file_sync_player_info_push_proto_rawDescGZIP(), []int{0}
}

// S -> C 同步玩家信息
type S2CSyncPlayerInfoPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"` // 玩家信息
}

func (x *S2CSyncPlayerInfoPush) Reset() {
	*x = S2CSyncPlayerInfoPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_player_info_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CSyncPlayerInfoPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSyncPlayerInfoPush) ProtoMessage() {}

func (x *S2CSyncPlayerInfoPush) ProtoReflect() protoreflect.Message {
	mi := &file_sync_player_info_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSyncPlayerInfoPush.ProtoReflect.Descriptor instead.
func (*S2CSyncPlayerInfoPush) Descriptor() ([]byte, []int) {
	return file_sync_player_info_push_proto_rawDescGZIP(), []int{1}
}

func (x *S2CSyncPlayerInfoPush) GetPlayerInfo() *PlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

var File_sync_player_info_push_proto protoreflect.FileDescriptor

var file_sync_player_info_push_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x43,
	0x32, 0x53, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x75, 0x73, 0x68, 0x22, 0x44, 0x0a, 0x15, 0x53, 0x32, 0x43, 0x53, 0x79, 0x6e, 0x63, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x12, 0x2b, 0x0a,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0xaa, 0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_player_info_push_proto_rawDescOnce sync.Once
	file_sync_player_info_push_proto_rawDescData = file_sync_player_info_push_proto_rawDesc
)

func file_sync_player_info_push_proto_rawDescGZIP() []byte {
	file_sync_player_info_push_proto_rawDescOnce.Do(func() {
		file_sync_player_info_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_player_info_push_proto_rawDescData)
	})
	return file_sync_player_info_push_proto_rawDescData
}

var file_sync_player_info_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_player_info_push_proto_goTypes = []interface{}{
	(*C2SSyncPlayerInfoPush)(nil), // 0: C2SSyncPlayerInfoPush
	(*S2CSyncPlayerInfoPush)(nil), // 1: S2CSyncPlayerInfoPush
	(*PlayerInfo)(nil),            // 2: PlayerInfo
}
var file_sync_player_info_push_proto_depIdxs = []int32{
	2, // 0: S2CSyncPlayerInfoPush.playerInfo:type_name -> PlayerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sync_player_info_push_proto_init() }
func file_sync_player_info_push_proto_init() {
	if File_sync_player_info_push_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sync_player_info_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SSyncPlayerInfoPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_player_info_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CSyncPlayerInfoPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_player_info_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_player_info_push_proto_goTypes,
		DependencyIndexes: file_sync_player_info_push_proto_depIdxs,
		MessageInfos:      file_sync_player_info_push_proto_msgTypes,
	}.Build()
	File_sync_player_info_push_proto = out.File
	file_sync_player_info_push_proto_rawDesc = nil
	file_sync_player_info_push_proto_goTypes = nil
	file_sync_player_info_push_proto_depIdxs = nil
}
