// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: wait_card_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 等待玩家碰杠吃胡 推送
type C2SWaitCardPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SWaitCardPush) Reset() {
	*x = C2SWaitCardPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wait_card_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SWaitCardPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SWaitCardPush) ProtoMessage() {}

func (x *C2SWaitCardPush) ProtoReflect() protoreflect.Message {
	mi := &file_wait_card_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SWaitCardPush.ProtoReflect.Descriptor instead.
func (*C2SWaitCardPush) Descriptor() ([]byte, []int) {
	return file_wait_card_push_proto_rawDescGZIP(), []int{0}
}

// S -> C 等待玩家碰杠吃胡 推送
type S2CWaitCardPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MustWin bool `protobuf:"varint,1,opt,name=MustWin,proto3" json:"MustWin,omitempty"` // 是否必须胡
}

func (x *S2CWaitCardPush) Reset() {
	*x = S2CWaitCardPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wait_card_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CWaitCardPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWaitCardPush) ProtoMessage() {}

func (x *S2CWaitCardPush) ProtoReflect() protoreflect.Message {
	mi := &file_wait_card_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWaitCardPush.ProtoReflect.Descriptor instead.
func (*S2CWaitCardPush) Descriptor() ([]byte, []int) {
	return file_wait_card_push_proto_rawDescGZIP(), []int{1}
}

func (x *S2CWaitCardPush) GetMustWin() bool {
	if x != nil {
		return x.MustWin
	}
	return false
}

var File_wait_card_push_proto protoreflect.FileDescriptor

var file_wait_card_push_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x75, 0x73, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x57, 0x61, 0x69,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x32, 0x43,
	0x57, 0x61, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x75, 0x73, 0x74, 0x57, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4d,
	0x75, 0x73, 0x74, 0x57, 0x69, 0x6e, 0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0xaa, 0x02,
	0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wait_card_push_proto_rawDescOnce sync.Once
	file_wait_card_push_proto_rawDescData = file_wait_card_push_proto_rawDesc
)

func file_wait_card_push_proto_rawDescGZIP() []byte {
	file_wait_card_push_proto_rawDescOnce.Do(func() {
		file_wait_card_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_wait_card_push_proto_rawDescData)
	})
	return file_wait_card_push_proto_rawDescData
}

var file_wait_card_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wait_card_push_proto_goTypes = []interface{}{
	(*C2SWaitCardPush)(nil), // 0: C2SWaitCardPush
	(*S2CWaitCardPush)(nil), // 1: S2CWaitCardPush
}
var file_wait_card_push_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wait_card_push_proto_init() }
func file_wait_card_push_proto_init() {
	if File_wait_card_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wait_card_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SWaitCardPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wait_card_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CWaitCardPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wait_card_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wait_card_push_proto_goTypes,
		DependencyIndexes: file_wait_card_push_proto_depIdxs,
		MessageInfos:      file_wait_card_push_proto_msgTypes,
	}.Build()
	File_wait_card_push_proto = out.File
	file_wait_card_push_proto_rawDesc = nil
	file_wait_card_push_proto_goTypes = nil
	file_wait_card_push_proto_depIdxs = nil
}
