// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: xuan_que.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C -> S 玩家选缺操作
type C2SXuanQue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hold     int32 `protobuf:"varint,1,opt,name=hold,proto3" json:"hold,omitempty"`         // 前端透传 保留 前端要求，合理性前端提供
	CardType int32 `protobuf:"varint,2,opt,name=CardType,proto3" json:"CardType,omitempty"` // 选的缺门花色
}

func (x *C2SXuanQue) Reset() {
	*x = C2SXuanQue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuan_que_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SXuanQue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SXuanQue) ProtoMessage() {}

func (x *C2SXuanQue) ProtoReflect() protoreflect.Message {
	mi := &file_xuan_que_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SXuanQue.ProtoReflect.Descriptor instead.
func (*C2SXuanQue) Descriptor() ([]byte, []int) {
	return file_xuan_que_proto_rawDescGZIP(), []int{0}
}

func (x *C2SXuanQue) GetHold() int32 {
	if x != nil {
		return x.Hold
	}
	return 0
}

func (x *C2SXuanQue) GetCardType() int32 {
	if x != nil {
		return x.CardType
	}
	return 0
}

// S -> C 玩家选缺操作
type S2CXuanQue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hold int32 `protobuf:"varint,1,opt,name=hold,proto3" json:"hold,omitempty"` // 前端透传 保留 前端要求，合理性前端提供
}

func (x *S2CXuanQue) Reset() {
	*x = S2CXuanQue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xuan_que_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CXuanQue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CXuanQue) ProtoMessage() {}

func (x *S2CXuanQue) ProtoReflect() protoreflect.Message {
	mi := &file_xuan_que_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CXuanQue.ProtoReflect.Descriptor instead.
func (*S2CXuanQue) Descriptor() ([]byte, []int) {
	return file_xuan_que_proto_rawDescGZIP(), []int{1}
}

func (x *S2CXuanQue) GetHold() int32 {
	if x != nil {
		return x.Hold
	}
	return 0
}

var File_xuan_que_proto protoreflect.FileDescriptor

var file_xuan_que_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x78, 0x75, 0x61, 0x6e, 0x5f, 0x71, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3c, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x58, 0x75, 0x61, 0x6e, 0x51, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x6f,
	0x6c, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x20,
	0x0a, 0x0a, 0x53, 0x32, 0x43, 0x58, 0x75, 0x61, 0x6e, 0x51, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x6f, 0x6c, 0x64,
	0x42, 0x0b, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0xaa, 0x02, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xuan_que_proto_rawDescOnce sync.Once
	file_xuan_que_proto_rawDescData = file_xuan_que_proto_rawDesc
)

func file_xuan_que_proto_rawDescGZIP() []byte {
	file_xuan_que_proto_rawDescOnce.Do(func() {
		file_xuan_que_proto_rawDescData = protoimpl.X.CompressGZIP(file_xuan_que_proto_rawDescData)
	})
	return file_xuan_que_proto_rawDescData
}

var file_xuan_que_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xuan_que_proto_goTypes = []interface{}{
	(*C2SXuanQue)(nil), // 0: C2SXuanQue
	(*S2CXuanQue)(nil), // 1: S2CXuanQue
}
var file_xuan_que_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xuan_que_proto_init() }
func file_xuan_que_proto_init() {
	if File_xuan_que_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xuan_que_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SXuanQue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xuan_que_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CXuanQue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xuan_que_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xuan_que_proto_goTypes,
		DependencyIndexes: file_xuan_que_proto_depIdxs,
		MessageInfos:      file_xuan_que_proto_msgTypes,
	}.Build()
	File_xuan_que_proto = out.File
	file_xuan_que_proto_rawDesc = nil
	file_xuan_que_proto_goTypes = nil
	file_xuan_que_proto_depIdxs = nil
}
